version: '3'

services:
  consulserver01:
    image: consul:1.10
    container_name: fullcycle_consulserver01
    hostname: consulserver01
    command: ['tail', '-f', '/dev/null']
  consulserver02:
    image: consul:1.10
    container_name: fullcycle_consulserver02
    hostname: consulserver02
    command: ['tail', '-f', '/dev/null']
  consulserver03:
    image: consul:1.10
    container_name: fullcycle_consulserver03
    hostname: consulserver03
    command: ['tail', '-f', '/dev/null']

  consulclient01:
    image: consul:1.10
    container_name: fullcycle_consulclient01
    hostname: consulclient01
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul01:/etc/consul.d
  consulclient02:
    image: consul:1.10
    container_name: fullcycle_consulclient02
    hostname: consulclient02
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul02:/etc/consul.d